jasypt:
  encryptor:
    bean: codeSheepEncryptorBean
    property:
      prefix: CodeSheep(
      suffix: )

address:
  audio:
    intercept: /music/**
    redirect: file:D:/music/
  video:
    intercept: /mv/**
    redirect: file:D:/videos/

spring:
  application:
    name: service=webflux
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot?charset=utf8mb4&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    # username: CodeSheep(B0oWefat1FSUCXd960e97MhEwhEynvfbX7G98pYogbmhRQz+R4yPvpeCdmtVfK/C)
    # password: CodeSheep(464B5T9zA9hu9wxv+Tln90ZSOT1PTDXAZg7XHkTKUohwXw+y6KJKP2krxy1lR6wi)
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true

server:
  port: 8181


